Replace Gitter link with Discord/
micronaut-projects/micronaut-starter-ui pull request #93
Opened 2023-09-26 20:56 UTC by wetted

closes #92

2023-09-29 07:38 UTC, sdelamo commented
I think this is blocked because of https://github.com/micronaut-projects/micronaut-starter-ui/issues/94

2023-09-29 08:25 UTC, timyates commented
I think adding this makes the Gradle task pass

```diff
diff --git a/build.gradle b/build.gradle
index ce28f3f..c0a11a0 100644
--- a/build.gradle
+++ b/build.gradle
@@ -18,6 +18,7 @@ node {
 task buildStarter(type: NpmTask) {
     dependsOn npmInstall
     workingDir = file("${rootProject.projectDir}/app/launch")
+    environment = [NODE_OPTIONS: '--openssl-legacy-provider']
     args = ['run', 'build']
 }
```

Which may unblock this, but we really should do #94 

I'm not sure why this is required either... Locally to run the apps, I seem to need to use

```
❯ nvm use v12.22.10
Now using node v12.22.10 (npm v6.14.16)
```

But the change being required seems to imply that the gradle build is using Node 17

I have no idea what's going on

2023-09-29 09:05 UTC, timyates requested changes

2023-09-29 09:05 UTC, timyates commented on app/launch/src/components/Links/DiscordLink.js
> +export default DiscordLink
```suggestion
export const DiscordLink = ({ className, theme }) => {
  const backgroundColor = theme === 'dark' ? 'var(--theme-light)' : 'var(--theme-dark)'
  const fill = theme === 'dark' ? '#000' : '#fff'

  return (
    <a
      href="https://discord.com/channels/1121511613250412714/1122324729756385300"
      aria-label="Micronaut Discord Channel"
      title="Micronaut Discord Channel"
      target="_blank"
      rel="noopener noreferrer"
      style={{
        backgroundColor,
      }}
      className={className}
    >
      <svg
        aria-hidden="true"
        focusable="false"
        viewBox="-50 -28.5 356 256"
      >
        <path d="M216.856339,16.5966031 C200.285002,8.84328665 182.566144,3.2084988 164.041564,0 C161.766523,4.11318106 159.108624,9.64549908 157.276099,14.0464379 C137.583995,11.0849896 118.072967,11.0849896 98.7430163,14.0464379 C96.9108417,9.64549908 94.1925838,4.11318106 91.8971895,0 C73.3526068,3.2084988 55.6133949,8.86399117 39.0420583,16.6376612 C5.61752293,67.146514 -3.4433191,116.400813 1.08711069,164.955721 C23.2560196,181.510915 44.7403634,191.567697 65.8621325,198.148576 C71.0772151,190.971126 75.7283628,183.341335 79.7352139,175.300261 C72.104019,172.400575 64.7949724,168.822202 57.8887866,164.667963 C59.7209612,163.310589 61.5131304,161.891452 63.2445898,160.431257 C105.36741,180.133187 151.134928,180.133187 192.754523,160.431257 C194.506336,161.891452 196.298154,163.310589 198.110326,164.667963 C191.183787,168.842556 183.854737,172.420929 176.223542,175.320965 C180.230393,183.341335 184.861538,190.991831 190.096624,198.16893 C211.238746,191.588051 232.743023,181.531619 254.911949,164.955721 C260.227747,108.668201 245.831087,59.8662432 216.856339,16.5966031 Z M85.4738752,135.09489 C72.8290281,135.09489 62.4592217,123.290155 62.4592217,108.914901 C62.4592217,94.5396472 72.607595,82.7145587 85.4738752,82.7145587 C98.3405064,82.7145587 108.709962,94.5189427 108.488529,108.914901 C108.508531,123.290155 98.3405064,135.09489 85.4738752,135.09489 Z M170.525237,135.09489 C157.88039,135.09489 147.510584,123.290155 147.510584,108.914901 C147.510584,94.5396472 157.658606,82.7145587 170.525237,82.7145587 C183.391518,82.7145587 193.761324,94.5189427 193.539891,108.914901 C193.539891,123.290155 183.391518,135.09489 170.525237,135.09489 Z"
              style={{ fill:fill }}
        />
      </svg>
    </a>
  )
}
export default DiscordLink
```

That gives:

<img width="319" alt="image" src="https://github.com/micronaut-projects/micronaut-starter-ui/assets/49317/3776cd83-7a4b-4076-bec0-ba094c0f8a22">

For light mode and

<img width="304" alt="image" src="https://github.com/micronaut-projects/micronaut-starter-ui/assets/49317/1e8c8c24-db8e-4a85-9d2b-7c39c6dca35e">

For dark mode

2023-09-29 14:46 UTC, timyates commented
> I have no idea what's going on

[I've raised a PR to update to the latest node plugin and gradle version (and update some of the packages)](https://github.com/micronaut-projects/micronaut-starter-ui/pull/95)

2023-09-29 14:54 UTC, timyates commented
To run this PR locally and see the result;

1. Run micronaut-starter locally with `CORS_ALLOWED_ORIGIN=http://localhost:3000 ./gradlew starter-web-netty:run`
2. In another terminal, in starter-ui run

```
cd dev-proxy-server && \
    rm -rf package-lock.json node_modules && \
    npm install && \
    npm run start:starter
```

3. In yet another terminal, run:

```
cd app/launch && \
    rm -rf package-lock.json node_modules && \
    npm install && \
    NODE_OPTIONS='--openssl-legacy-provider' npm run start:local
```

Your browser should open to http://localhost:3000/launch

2023-10-03 11:34 UTC, sdelamo commented
It looks black to me 
![CleanShot 2023-10-03 at 13 34 04@2x](https://github.com/micronaut-projects/micronaut-starter-ui/assets/864788/20297f55-0c04-4d84-905f-8207284256c3)

2023-10-03 11:36 UTC, timyates commented
[With the updated discord.js](https://github.com/micronaut-projects/micronaut-starter-ui/pull/93#pullrequestreview-1650369760)?

Which browser is that in?

2023-10-03 11:38 UTC, timyates commented
Ahh yes... it's black in safari 🫠 looking...

2023-10-03 11:43 UTC, timyates commented
@sdelamo can you try now?

2023-10-03 11:45 UTC, timyates approved these changes

2023-10-03 11:47 UTC, sdelamo requested changes
It displays a black circle

2023-10-03 11:48 UTC, sdelamo approved these changes
Thanks @timyates

2023-10-03 11:48 UTC, merged