Update Gradle to 8.3, and node plugin to latest
micronaut-projects/micronaut-starter-ui pull request #95
Opened 2023-09-29 13:07 UTC by timyates

Also updated some dependencies.

I don't think we can move to react 18 without a big upgrade of the material-ui libs.

I'm not 100% this is correct, but it builds, and I can dev locally against a local starter.

Closes #94

2023-09-29 15:25 UTC, jeremyg484 requested changes
Looks good overall and works locally for me, just need to clarify the instructions as noted.

I agree that trying to upgrade to React 18 is probably not worth the trouble at the moment.

2023-09-29 15:39 UTC, timyates commented on README.md
> +CORS_ALLOWED_ORIGIN=http://localhost:3000 ./gradlew starter-web-netty:run
Pulled the clone bit up here and hopefully made it more explicit 🤞😎

2023-09-29 15:39 UTC, timyates commented on README.md
> -./gradlew starter-web-netty:run
👍

2023-09-29 15:39 UTC, timyates commented on README.md
> +npm run start:local
Good catch

👍

2023-09-29 15:40 UTC, timyates commented on README.md
> +## Previous instructions...
Gone now... We'll always have git history!

2023-09-29 15:41 UTC, timyates commented on build.gradle.kts
> +import com.github.gradle.node.npm.task.NpmTask
I really don't know...  I assume there were reasons at some point...  Maybe gradle handles the npm/node installation requirement better than anything available at the time of this repo's birth 🤔

2023-09-29 15:42 UTC, timyates commented on README.md
> +CORS_ALLOWED_ORIGIN=http://localhost:3000 ./gradlew starter-web-netty:run
https://github.com/micronaut-projects/micronaut-starter-ui/blob/32c68f2eb8c8648e8119d483d647a62b5ca5d02f/README.md is easier to reads than diffs ;-)

2023-09-29 16:42 UTC, jeremyg484 commented on build.gradle.kts
> +import com.github.gradle.node.npm.task.NpmTask
Fair enough. It's simple enough usage that it's not worth changing at the moment.

2023-09-29 16:44 UTC, jeremyg484 commented on README.md
> +CORS_ALLOWED_ORIGIN=http://localhost:3000 ./gradlew starter-web-netty:run
Yea, I cloned your branch to make sure I could work through the instructions successfully. Looking good now.

2023-09-29 16:45 UTC, jeremyg484 approved these changes

2023-10-02 04:50 UTC, sdelamo reviewed
Thanks for this PR @timyates  🙌

Do I need a different `node` version to run it locally?

```
% npm -v                  
10.1.0
sdelamo@Sergios-Mac-Studio micronaut-starter-ui % node -v                 
v18.17.1
sdelamo@Sergios-Mac-Studio micronaut-starter-ui % java --version
openjdk 17.0.8 2023-07-18 LTS
OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (build 17.0.8+7-LTS, mixed mode, sharing)
sdelamo@Sergios-Mac-Studio micronaut-starter-ui % ./gradlew build

> Configure project :
Kotlin DSL property assignment is an incubating feature.

> Task :buildStarter FAILED

> app@0.1.1 build
> react-scripts build

node:internal/modules/cjs/loader:446
      throw err;
      ^

Error: Cannot find module '/Users/sdelamo/github/micronaut-projects/micronaut-starter-ui/app/launch/node_modules/tryer/src/tryer'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/sdelamo/github/micronaut-projects/micronaut-starter-ui/app/launch/node_modules/bfj/src/streamify.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/sdelamo/github/micronaut-projects/micronaut-starter-ui/app/launch/node_modules/tryer/package.json',
  requestPath: 'tryer'
}

Node.js v18.17.1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildStarter'.
> Process 'command '/Users/sdelamo/github/micronaut-projects/micronaut-starter-ui/.gradle/nodejs/node-v18.17.1-darwin-arm64/bin/npm'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
```

2023-10-02 08:29 UTC, timyates commented
@sdelamo You shouldn't do, as now it downloads and installs a version of node to build the app

So it's being built with

```
> Process 'command '/Users/sdelamo/github/micronaut-projects/micronaut-starter-ui/.gradle/nodejs/node-v18.17.1-darwin-arm64/bin/npm'' finished with non-zero exit value 1
```

Can you try removing your node_modules directory with

```
rm -rf app/launch/node_modules
```

And then try again?

2023-10-03 11:31 UTC, sdelamo commented
I tried with a different computer and it loaded 🤷🏻‍♂️

2023-10-03 11:31 UTC, merged